env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  import/no-unresolved: [warn]
  max-len: [off]
  no-await-in-loop: [warn]
  no-multi-spaces: [off]
  no-multi-str: [off]
  no-useless-escape: [off]
  object-curly-newline: [off]
